name: Daily VFS Appointment Check

on:
  schedule:
    - cron: "30 22 * * *"  # Runs at 8:30 AM Melbourne time (22:30 UTC previous day)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'  # Fetch Turnstile-Solver submodule if needed

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Increase system limits
      run: |
        # Increase file limit
        ulimit -n 65535 || echo "Failed to increase file limit - proceeding anyway"
        # Display limits
        echo "Current file limits:"
        ulimit -a

    - name: Setup Python for Turnstile Solver (optional)
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies for puppeteer-real-browser
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libatk1.0-0 \
          libc6 \
          libcairo2 \
          libcups2 \
          libdbus-1-3 \
          libexpat1 \
          libfontconfig1 \
          libgbm1 \
          libgdk-pixbuf2.0-0 \
          libglib2.0-0 \
          libgtk-3-0 \
          libnspr4 \
          libpango-1.0-0 \
          libpangocairo-1.0-0 \
          libstdc++6 \
          libx11-6 \
          libx11-xcb1 \
          libxcb1 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxext6 \
          libxfixes3 \
          libxi6 \
          libxrandr2 \
          libxrender1 \
          libxss1 \
          libxtst6 \
          ca-certificates \
          fonts-liberation \
          libnss3 \
          lsb-release \
          xdg-utils \
          wget \
          xvfb

    - name: Install Node.js dependencies
      run: npm install

    - name: Setup Chrome
      run: |
        # Install Google Chrome stable
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | gpg --dearmor | sudo tee /usr/share/keyrings/google-chrome.gpg > /dev/null
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
        # Verify Chrome installation
        google-chrome-stable --version
        which google-chrome-stable

    - name: Run VFS appointment check
      env:
        VFS_EMAIL: ${{ secrets.VFS_EMAIL }}
        VFS_PASSWORD: ${{ secrets.VFS_PASSWORD }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_SENDER_PASS: ${{ secrets.EMAIL_SENDER_PASS }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        CI: true
        DISPLAY: :99
        PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome-stable
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
        NODE_OPTIONS: "--max-old-space-size=4096"
      run: |
        # Start virtual display for puppeteer-real-browser
        echo "Starting Xvfb..."
        Xvfb :99 -screen 0 1920x1080x24 > /dev/null 2>&1 &
        sleep 5
        
        # Verify Xvfb is running
        ps aux | grep Xvfb
        
        # Verify display setup
        echo "Display: $DISPLAY"
        echo "Puppeteer executable path: $PUPPETEER_EXECUTABLE_PATH"
        
        # We don't need to modify index.js anymore since it already has CI detection
        # Just verify the file exists and is valid JavaScript
        node -e '
          try {
            require("./index.js");
            console.log("✅ index.js is syntactically valid");
          } catch (error) {
            console.error("❌ Error with index.js:", error);
            process.exit(1);
          }
        '
        
        # Run the appointment check
        echo "Starting appointment check..."
        node --unhandled-rejections=strict index.js

    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: vfs-check-screenshots-${{ github.run_number }}
        path: "*.png"
        retention-days: 30

