name: Daily VFS Appointment Check

on:
  schedule:
    - cron: "30 22 * * *"  # Runs at 8:30 AM Melbourne time (22:30 UTC previous day)
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install Node.js dependencies
      run: |
        npm install

    - name: Install system dependencies for Puppeteer
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          libnss3-dev \
          libatk-bridge2.0-dev \
          libdrm-dev \
          libxcomposite-dev \
          libxdamage-dev \
          libxrandr-dev \
          libgbm-dev \
          libxss-dev \
          libasound2-dev \
          libatspi2.0-dev \
          libgtk-3-dev

    - name: Run VFS appointment check
      env:
        VFS_EMAIL: ${{ secrets.VFS_EMAIL }}
        VFS_PASSWORD: ${{ secrets.VFS_PASSWORD }}
        EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
        EMAIL_SENDER_PASS: ${{ secrets.EMAIL_SENDER_PASS }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        CI: true
      run: node index.js

    - name: Upload screenshots
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: vfs-check-screenshots-${{ github.run_number }}
        path: "*.png"
        retention-days: 30

